# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

repos:
  CRAN: https://cloud.r-project.org

r_packages:
  - ggplot2
    
install: skip

script:
  - Rscript runme.R